prepare to run tests after installing package php-vitexsoftware-ease-core-dev

diff --git a/debian/php-vitexsoftware-ease-core-dev.postinst b/debian/php-vitexsoftware-ease-core-dev.postinst
--- a/debian/php-vitexsoftware-ease-core-dev.postinst
+++ b/debian/php-vitexsoftware-ease-core-dev.postinst
@@ -1,14 +1,47 @@
 #!/bin/sh
+
+#DEBHELPER#
+
 # postinst script for php-vitexsoftware-ease-core-dev
+#
+# see: dh_installdeb(1)
 
 set -e
 
-. /usr/share/debconf/confmodule
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-db_get composer/WEB_USER
-WEBUSER=$RET
-mkdir -p /var/lib/php-vitexsoftware-ease-core
-chown $WEBUSER /var/lib/php-vitexsoftware-ease-core /var/lib/composer -R
-echo '{}' > /usr/share/php/EaseCore/composer.lock
-chown $WEBUSER /usr/share/php/EaseCore/composer.lock
-su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer -o install -d /usr/share/php/EaseCore/'
+
+case "$1" in
+    configure)
+
+        composer-global-update deb/ease-core-dev
+
+	phpunit --bootstrap /usr/share/php/EaseCoreTests/Bootstrap.php --configuration /usr/share/php/EaseCoreTests/phpunit.xml
+
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+exit 0
+
+#DEBHELPER#
